# Generated by Django 5.0.4 on 2024-05-09 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('theme', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expected_tuition', models.DecimalField(decimal_places=2, max_digits=10)),
                ('board_passing_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.college')),
            ],
        ),
    ]
