# Generated by Django 5.0.6 on 2024-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_requirement_alter_schedule_application_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycourse',
            name='board_passing_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
