# Generated by Django 5.0.6 on 2024-05-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_universitycourse_board_passing_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitycourse',
            name='estimated_tuition',
        ),
        migrations.AddField(
            model_name='universitycourse',
            name='estimated_tuition_maximum',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='universitycourse',
            name='estimated_tuition_minimum',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
