# Generated by Django 5.0.6 on 2024-05-11 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_universitycourse_estimated_tuition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.university'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UniversityRequirement',
        ),
    ]
