# Generated by Django 5.0.6 on 2024-05-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_requirement_university_delete_universityrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logoUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universitycourse',
            name='board_passing_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
